name: online_edu_app_flutter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ДОБАВЛЯЕМ ЭТОТ ПАКЕТ ДЛЯ ИНТЕГРАЦИИ ЛОКАЛИЗАЦИИ
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  file_picker: ^8.0.5
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.0.1
  image: ^4.2.0 

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  youtube_player_flutter: ^9.0.1
  youtube_player_iframe: ^5.1.2 
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  # ЭТА СТРОКА ВКЛЮЧАЕТ АВТОМАТИЧЕСКУЮ ГЕНЕРАЦИЮ КОДА ДЛЯ ПЕРЕВОДОВ
  generate: true