// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUpT0t9uZZZ5B3sa3Gu3XzpW8xpndGWMo',
    appId: '1:587613420902:web:053da0f94f47b9648e5ca7',
    messagingSenderId: '587613420902',
    projectId: 'online-edu-app',
    authDomain: 'online-edu-app.firebaseapp.com',
    storageBucket: 'online-edu-app.firebasestorage.app',
    measurementId: 'G-PBQNCG4LCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJMg5a0J6vQgGnZ15L-ziVjJCej8XYm8',
    appId: '1:587613420902:android:bf4f189499cd9e908e5ca7',
    messagingSenderId: '587613420902',
    projectId: 'online-edu-app',
    storageBucket: 'online-edu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3QjVnINbLKbnWjXcYG4oYAOu0hg05EaM',
    appId: '1:587613420902:ios:3220e5bcfa1b3b738e5ca7',
    messagingSenderId: '587613420902',
    projectId: 'online-edu-app',
    storageBucket: 'online-edu-app.firebasestorage.app',
    iosBundleId: 'com.example.onlineEduAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3QjVnINbLKbnWjXcYG4oYAOu0hg05EaM',
    appId: '1:587613420902:ios:3220e5bcfa1b3b738e5ca7',
    messagingSenderId: '587613420902',
    projectId: 'online-edu-app',
    storageBucket: 'online-edu-app.firebasestorage.app',
    iosBundleId: 'com.example.onlineEduAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUpT0t9uZZZ5B3sa3Gu3XzpW8xpndGWMo',
    appId: '1:587613420902:web:15d8713a620020528e5ca7',
    messagingSenderId: '587613420902',
    projectId: 'online-edu-app',
    authDomain: 'online-edu-app.firebaseapp.com',
    storageBucket: 'online-edu-app.firebasestorage.app',
    measurementId: 'G-2KXE097V8R',
  );

}